test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  keyfile: {
    type: "service_account",
    project_id: "simple-todo-kamoshare",
    private_key_id: <%= Rails.application.credentials.private_key_id %>,
    private_key: <%= Rails.application.credentials.private_key %>,
    client_email: "active-storage@simple-todo-kamoshare.iam.gserviceaccount.com",
    client_id: "106561806447430788539",
    auth_uri: "https://accounts.google.com/o/oauth2/auth",
    token_uri: "https://oauth2.googleapis.com/token",
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs",
    client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/active-storage%40simple-todo-kamoshare.iam.gserviceaccount.com"
  }
  project: "simple-todo-kamoshare"
  bucket: "simple-todo-kamoshare"

mirror:
  service: Mirror
  primary: local
  mirrors: [ google ]
